# Generated by Django 3.0.2 on 2020-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('phone', models.CharField(default='', max_length=111)),
                ('clothes_detail', models.CharField(max_length=5000)),
                ('quantity', models.CharField(max_length=300)),
            ],
        ),
    ]
