# Generated by Django 3.0.2 on 2020-01-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='select',
            fields=[
                ('select_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
