# Generated by Django 3.0.2 on 2020-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='image',
            field=models.ImageField(default='', upload_to='selectedimages'),
        ),
    ]
