# Generated by Django 3.0.2 on 2020-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200119_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('fulllength', models.CharField(max_length=90)),
                ('seleves', models.CharField(max_length=111)),
                ('chest', models.CharField(max_length=111)),
                ('west', models.CharField(default='', max_length=111)),
                ('heap', models.CharField(max_length=5000)),
                ('shoulder', models.CharField(max_length=111)),
            ],
        ),
    ]
