# Generated by Django 3.0.2 on 2020-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
