# Generated by Django 3.0 on 2019-12-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='Addition',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='Author',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='BookDetail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
