# Generated by Django 3.0 on 2019-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191227_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=70)),
                ('Password', models.CharField(default='', max_length=70)),
                ('Repassword', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
