# Generated by Django 3.0 on 2019-12-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
