# Generated by Django 3.0 on 2020-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_loginform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
